"""Tests for hermes_cli.jarvis_prime.job_store.JobStore.

Every test passes an explicit ``root`` so the file is runnable in isolation
outside the hermes-agent conftest. The one ``HERMES_HOME`` default-root test
exercises the lazy ``get_hermes_home()`` integration.
"""

import json
from pathlib import Path

import pytest

from hermes_cli.jarvis_prime.job_store import JobStore


@pytest.fixture()
def store(tmp_path: Path) -> JobStore:
    return JobStore(root=tmp_path / "jobs")


# ---------------------------------------------------------------------------
# Directory layout
# ---------------------------------------------------------------------------


class TestCreateJob:
    def test_builds_directory_shape(self, store: JobStore):
        record = store.create_job({"prompt": "hello"})
        jdir = store.job_dir(record["id"])
        assert jdir.is_dir()
        assert (jdir / "job.json").is_file()
        assert (jdir / "ledger.jsonl").is_file()
        assert (jdir / "ledger.jsonl").read_text() == ""
        assert (jdir / "artifacts").is_dir()
        assert (jdir / "reports").is_dir()

    def test_autogenerated_id_is_12_hex(self, store: JobStore):
        record = store.create_job()
        jid = record["id"]
        assert len(jid) == 12
        assert all(c in "0123456789abcdef" for c in jid)
        assert (store.root / jid).is_dir()

    def test_caller_supplied_id_is_honoured(self, store: JobStore):
        record = store.create_job({"x": 1}, job_id="abc123")
        assert record["id"] == "abc123"
        assert (store.root / "abc123" / "job.json").is_file()

    def test_rejects_duplicate_id(self, store: JobStore):
        store.create_job(job_id="dup")
        with pytest.raises(FileExistsError):
            store.create_job(job_id="dup")

    def test_persists_caller_fields_alongside_bookkeeping(self, store: JobStore):
        record = store.create_job({"prompt": "p", "state": "queued"})
        on_disk = json.loads(store._job_file(record["id"]).read_text())
        assert on_disk["prompt"] == "p"
        assert on_disk["state"] == "queued"
        assert on_disk["id"] == record["id"]
        assert "created_at" in on_disk
        assert on_disk["created_at"] == on_disk["updated_at"]

    def test_data_id_cannot_override_explicit_job_id(self, store: JobStore):
        record = store.create_job({"id": "fake"}, job_id="real")
        assert record["id"] == "real"
        on_disk = json.loads(store._job_file("real").read_text())
        assert on_disk["id"] == "real"


# ---------------------------------------------------------------------------
# Load / save / list / delete
# ---------------------------------------------------------------------------


class TestLoadSave:
    def test_load_roundtrips_caller_fields(self, store: JobStore):
        record = store.create_job({"prompt": "p", "nested": {"a": 1}})
        loaded = store.load_job(record["id"])
        assert loaded["prompt"] == "p"
        assert loaded["nested"] == {"a": 1}
        assert loaded["id"] == record["id"]

    def test_load_missing_raises_filenotfound(self, store: JobStore):
        with pytest.raises(FileNotFoundError):
            store.load_job("nope")

    def test_save_preserves_id_and_created_at(self, store: JobStore):
        record = store.create_job({"prompt": "old"})
        jid = record["id"]
        original_created = record["created_at"]

        saved = store.save_job(jid, {"prompt": "new", "id": "hijack", "created_at": "1999-01-01T00:00:00+00:00"})
        assert saved["id"] == jid
        assert saved["created_at"] == original_created
        assert saved["prompt"] == "new"

        on_disk = store.load_job(jid)
        assert on_disk["id"] == jid
        assert on_disk["created_at"] == original_created
        assert on_disk["prompt"] == "new"

    def test_save_bumps_updated_at(self, store: JobStore):
        import time

        record = store.create_job({"prompt": "p"})
        # Sleep > 1s so the second ISO timestamp (second precision) differs.
        time.sleep(1.1)
        saved = store.save_job(record["id"], {"prompt": "p2"})
        assert saved["updated_at"] >= record["updated_at"]
        assert saved["updated_at"] != record["created_at"]

    def test_save_missing_raises_filenotfound(self, store: JobStore):
        with pytest.raises(FileNotFoundError):
            store.save_job("nope", {"prompt": "x"})

    def test_save_leaves_no_tempfiles(self, store: JobStore):
        record = store.create_job({"prompt": "p"})
        store.save_job(record["id"], {"prompt": "p2"})
        leftover = list(store.job_dir(record["id"]).glob(".job_*.tmp"))
        assert leftover == []


class TestListJobs:
    def test_returns_sorted_ids(self, store: JobStore):
        store.create_job(job_id="c")
        store.create_job(job_id="a")
        store.create_job(job_id="b")
        assert store.list_jobs() == ["a", "b", "c"]

    def test_skips_orphan_dirs_without_job_json(self, store: JobStore):
        store.create_job(job_id="real")
        (store.root / "orphan").mkdir()
        assert store.list_jobs() == ["real"]

    def test_empty_store(self, store: JobStore):
        assert store.list_jobs() == []


class TestDeleteJob:
    def test_removes_directory_tree(self, store: JobStore):
        record = store.create_job({"prompt": "p"})
        jid = record["id"]
        jdir = store.job_dir(jid)
        # Drop a sentinel inside artifacts to ensure recursive removal.
        (jdir / "artifacts" / "x.txt").write_text("data")

        assert store.delete_job(jid) is True
        assert not jdir.exists()

    def test_missing_returns_false(self, store: JobStore):
        assert store.delete_job("nope") is False


# ---------------------------------------------------------------------------
# Ledger
# ---------------------------------------------------------------------------


class TestLedger:
    def test_append_injects_ts_when_absent(self, store: JobStore):
        record = store.create_job({"prompt": "p"})
        written = store.append_ledger(record["id"], {"event": "started"})
        assert "ts" in written
        # Round-trip via disk to make sure the ts landed there too.
        entries = store.read_ledger(record["id"])
        assert len(entries) == 1
        assert entries[0]["event"] == "started"
        assert entries[0]["ts"] == written["ts"]

    def test_append_preserves_caller_ts(self, store: JobStore):
        record = store.create_job()
        caller_ts = "1999-12-31T23:59:59+00:00"
        store.append_ledger(record["id"], {"event": "manual", "ts": caller_ts})
        entries = store.read_ledger(record["id"])
        assert entries[0]["ts"] == caller_ts

    def test_append_is_append_only(self, store: JobStore):
        record = store.create_job()
        for n in range(3):
            store.append_ledger(record["id"], {"event": f"e{n}", "ts": f"t{n}"})
        entries = store.read_ledger(record["id"])
        assert [e["event"] for e in entries] == ["e0", "e1", "e2"]
        # Disk view: exactly three non-empty lines.
        raw = (store.job_dir(record["id"]) / "ledger.jsonl").read_text()
        assert [ln for ln in raw.splitlines() if ln.strip()] == raw.splitlines()
        assert len(raw.splitlines()) == 3

    def test_append_rejects_non_dict(self, store: JobStore):
        record = store.create_job()
        with pytest.raises(TypeError):
            store.append_ledger(record["id"], "not a dict")  # type: ignore[arg-type]

    def test_append_missing_job_raises(self, store: JobStore):
        with pytest.raises(FileNotFoundError):
            store.append_ledger("nope", {"event": "x"})

    def test_read_ledger_returns_empty_when_no_appends(self, store: JobStore):
        record = store.create_job()
        assert store.read_ledger(record["id"]) == []

    def test_read_ledger_skips_malformed_lines(self, store: JobStore, caplog):
        record = store.create_job()
        store.append_ledger(record["id"], {"event": "ok1"})
        # Inject a corrupt line by hand.
        with open(store.job_dir(record["id"]) / "ledger.jsonl", "a", encoding="utf-8") as f:
            f.write("not-json\n")
        store.append_ledger(record["id"], {"event": "ok2"})

        entries = store.read_ledger(record["id"])
        assert [e["event"] for e in entries] == ["ok1", "ok2"]

    def test_read_ledger_missing_file_returns_empty(self, store: JobStore):
        # Read for a job that does not exist — no ledger file, no error.
        assert store.read_ledger("nope") == []


# ---------------------------------------------------------------------------
# Default root via get_hermes_home()
# ---------------------------------------------------------------------------


class TestDefaultRoot:
    def test_default_root_follows_hermes_home(self, tmp_path: Path, monkeypatch):
        monkeypatch.setenv("HERMES_HOME", str(tmp_path))
        s = JobStore()
        assert s.root == (tmp_path / "jobs").resolve()
        assert s.root.is_dir()

    def test_explicit_root_overrides_env(self, tmp_path: Path, monkeypatch):
        monkeypatch.setenv("HERMES_HOME", str(tmp_path / "ignored"))
        custom = tmp_path / "custom"
        s = JobStore(root=custom)
        assert s.root == custom.resolve()

    def test_default_root_is_resolved_lazily(self, tmp_path: Path, monkeypatch):
        # Construct first, redirect HERMES_HOME after — the redirect must win.
        s = JobStore()
        monkeypatch.setenv("HERMES_HOME", str(tmp_path))
        assert s.root == (tmp_path / "jobs").resolve()


# ---------------------------------------------------------------------------
# Misc API guards
# ---------------------------------------------------------------------------


def test_empty_job_id_raises(store: JobStore):
    with pytest.raises(ValueError):
        store.job_dir("")
